mysql:
  image: mysql:5.6
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=rack
api:
  image: quay.io/rack/api-server
  ports:
    - "8088:8088"
  links:
    - mysql
