---
- name: td-agent packages for openstack and fluentd_collector nodes
  hosts: openstack:fluentd_collector
  gather_facts: yes
  sudo: yes
  tasks:
    # 
    - name: GPG key import
      rpm_key: state=present key=http://packages.treasuredata.com/GPG-KEY-td-agent

    - name: add repository
      copy: 
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0644
      with_items: 
        - { src: templates/etc/yum.repos.d/treasure-data.repo, dest: /etc/yum.repos.d/treasure-data.repo }

    
    - name: yum clean all
      command: /usr/bin/yum clean all
    
    - name: ensure fluentd packages are installed
      yum: name={{item}} state=latest
      with_items:
        - td-agent
        - td-libyaml

    - name: ensure td-agent automatically starts after reboot
      service: name={{item}} enabled=yes
      with_items:
        - td-agent        
        
        
  handlers:
    - include: ../reusables/handlers.yml



  
