---
- name: td-agent for openstack nodes installation
  hosts: openstack
  gather_facts: yes
  sudo: yes
  tasks:

    - name: ensure necessary plugins are installed
      command: /usr/lib64/fluent/ruby/bin/fluent-gem install {{item}}
      with_items:
        - fluent-plugin-tail-ex
        - fluent-plugin-record-reformer
        
    - name: ensure fluentd configuration file is updated
      template: >
          src=templates/etc/td-agent/td_agent.conf
          dest=/etc/td-agent/td-agent.conf
          owner=root
          group=root
          mode=0644
          backup=yes
      notify:
        - ensure td-agent is restarted   
        
    - name: ensure fluentd can access openstack log directories
      file: >
        path={{item}}
        mode=0755
        state=directory
      with_items:
        - /var/log/cinder
        - /var/log/glance
        - /var/log/httpd
        - /var/log/keystone
        - /var/log/neutron
        - /var/log/nova 
        
    - name: ensure td-agent automatically starts after reboot
      service: name={{item}} enabled=yes
      with_items:
        - td-agent        
        
        
  handlers:
    - name: ensure td-agent is restarted 
      service: name={{ item }} state=restarted
      with_items:
        - td-agent




  
