---
- name: td-agent setup for fluend-collector node
  hosts: fluentd_collector
  gather_facts: yes
  sudo: yes
  tasks:
    - name: ensure fluentd packages are installed
      yum: name={{item}} state=latest
      with_items:
        - ruby-devel  
        - gcc
        - libcurl-devel
  
    - name: ensure necessary plugins are installed
      command: /usr/lib64/fluent/ruby/bin/fluent-gem install {{item}}
      with_items:
        - fluent-plugin-tail-ex
        - fluent-plugin-record-reformer
        - fluent-plugin-elasticsearch
        
    - name: ensure fluentd configuration for fluentd_collector is installed
      template: >
          src=templates/etc/td-agent/td_agent_collector.conf
          dest=/etc/td-agent/td-agent.conf
          owner=root
          group=root
          mode=0644
          backup=yes
      notify:
        - ensure td-agent is restarted   
        
    - name: ensure keystone port fluentd_collector_ip is opened
      include: ../reusables/open_firewall_port.yml protocol=tcp port="{{ fluentd_collector_port }}"

    - name: ensure keystone port of UDP is also opened
      include: ../reusables/open_firewall_port.yml protocol=udp port="{{ fluentd_collector_port }}"
        
    - name: ensure td-agent automatically starts after reboot
      service: name={{item}} enabled=yes
      with_items:
        - td-agent        
        
  handlers:
    - include: ../reusables/handlers.yml

    - name: ensure td-agent is restarted 
      service: name={{ item }} state=restarted
      with_items:
        - td-agent




  
