---
- name: NTP Server
  hosts: all
  sudo: yes

  tasks:
    - name: ensure ntp package is installed
      yum: name=ntp state=latest
      when: "ntp_server is defined"
  
    - name: ensure ntp.conf file is configured
      template: >
             src=templates/etc/ntp.conf
             dest=/etc/ntp.conf
             owner=root
             group=root
             mode=0644
      notify: restart ntp
      when: "ntp_server is defined"
  
    - name: synchronize clock now.
      command: /usr/sbin/ntpdate -bu {{ ntp_server }}
      when: "ntp_server is defined"
  
  
  handlers:
    - name: restart ntp
      service: name=ntpd state=restarted enabled=on






