---
- name: determine networks of elasticsearch/fluentd/Kibana
  hosts: fluentd_collector:elasticsearch:Kibana
  gather_facts: yes
  sudo: yes

  tasks:

    - name: ensure my_int_ip is a fact variable
      action: set_fact
      args:
        my_int_ip: "{{ my_int_ip }}"
   
      
    - name: ensure my_mng_ip is a fact variable
      action: set_fact
      args:
        my_mng_ip: "{{ my_mng_ip }}"

