---
- name: OpenStack Block Storage (Backend)
  hosts: volume_backend
  sudo: yes

  tasks:
   
    - name: ensure cinder-related packages are installed
      yum: name={{item}}  state=latest
      with_items:
        - openstack-cinder
        - openstack-utils
        - openstack-selinux
        - MySQL-python
      notify:
       - restart cinder services

    - name: ensure cinder.conf file is configured
      template: >
        src=templates/etc/cinder/cinder.conf
        dest=/etc/cinder/cinder.conf
        owner=root group=cinder mode=0640 backup=no
      notify:
       - restart cinder services

     
  
    - name: ensure cinder volume group is created
      lvg: 
        vg: "{{ cinder_volume }}"
        pvs: "{{ cinder_volume_dev }}" 
        state: present
        vg_options: ""
      notify:
       - restart cinder services
  
    - name: ensure tgtd.conf is configured
      lineinfile: > 
       dest=/etc/tgt/targets.conf
       state=present 
       line="include /etc/cinder/volumes/*"

    - name: ensure cinder and tgtd automatically boots after reboot
      service: name={{ item }} state=started enabled=yes
      with_items: 
        - openstack-cinder-volume
        - tgtd
        
    - name: ensure iscsi port 3260 is opened
      include: ../reusables/open_firewall_port.yml protocol=tcp port=3260
      
      
  handlers:
    - include: ../reusables/handlers.yml
    - name: restart cinder services
      service: name={{item}} state=restarted
      with_items:
        - openstack-cinder-volume 
        - tgtd
  
    